# Generated by Django 6.0.3 on 2026-03-14 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('college', 'College Fee'), ('special', 'Special Fee'), ('exam', 'Exam Fee')], max_length=10)),
                ('image', models.ImageField(upload_to='receipts/')),
                ('extracted_text', models.TextField(blank=True)),
                ('text_hash', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fee.receipt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
