# Generated by Django 6.0.3 on 2026-03-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='utr',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
