# Generated by Django 6.0.3 on 2026-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_receipt_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='transaction_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
