# Generated by Django 6.0.3 on 2026-03-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_receipt_transaction_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='hallticket_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
