# Generated by Django 6.0.1 on 2026-03-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='exam_category',
            field=models.CharField(blank=True, choices=[('regular', 'Regular Exam'), ('supply', 'Supply Exam')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='exam_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
