# Generated by Django 6.0.1 on 2026-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0007_receipt_exam_category_receipt_exam_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
