# Generated by Django 6.0.1 on 2026-03-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0010_receipt_academic_year_receipt_regulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='regulation',
            field=models.CharField(blank=True, choices=[('r18', 'R18'), ('r22', 'R22')], max_length=10, null=True),
        ),
    ]
