# Generated by Django 6.0.1 on 2026-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0011_studentprofile_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='regulation',
            field=models.CharField(blank=True, choices=[('r18', 'R18'), ('r22', 'R22'), ('r25', 'R25')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='regulation',
            field=models.CharField(blank=True, choices=[('r18', 'R18'), ('r22', 'R22'), ('r25', 'R25')], max_length=10, null=True),
        ),
    ]
