# Generated by Django 6.0.1 on 2026-03-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0012_alter_receipt_regulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('CSM', 'CSE (AI & ML)'), ('ECE', 'Electronics & Communication'), ('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('CSM', 'CSE (AI & ML)'), ('ECE', 'Electronics & Communication'), ('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering')], max_length=10, null=True),
        ),
    ]
