# Generated by Django 6.0.1 on 2026-04-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0014_receipt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
